### ISSUE TITLE
NuGet package for .NET 4.0+?

### ISSUE THREAD

**Issue by w0rd-driven** [azzlack/WebApi.DocumentationGenerator#1]
In my initial run through I didn't see anything that specifically required this to target .NET 4.5 specifically. I know ASP.NET 4 is included in 4.5 by default but VS2010 does have support for it.

Thanks

**Comment by azzlack** [comment]
WebAPI requires .NET 4.5, and this package requires WebAPI. Therefore it also requires .NET 4.5. :-)

**Comment by ducpho** [comment]
WebAPI doesn't require .NET 4.5. It also runs on ASP.NET 4.0.
